# MNIST data set analysis
Objective: Correctly classify clothes into ten categories: (0) T-shirt/top, (1) Trouser, (2) Pullover, (3) Dress, (4)
Coat, (5) Sandal, (6) Shirt, (7) Sneaker, (8) Bag, and 9) Ankle boot<br>
Details about the data set can be found on https://www.kaggle.com/zalando-research/fashionmnist

Task 1: Loading required libraries

In [1]:
import os
import subprocess
from IPython.display import display, HTML, Image
import io
from operator import itemgetter

from TAS_Python_Utilities import data_viz
from TAS_Python_Utilities import data_viz_target
from TAS_Python_Utilities import visualize_tree

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.tree import export_graphviz
from sklearn import tree
from sklearn import metrics
from sklearn import tree
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn import linear_model
from sklearn import neighbors

%matplotlib inline
%qtconsole

Task 2: Loading the data set that will be used to train and validade the algorithm

In [3]:
TrainValidationset = pd.read_csv('fashion-mnist_train.csv')

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

Task 3: Exploration of the training set

In [4]:
TrainValidationset["label"].value_counts()

9    6000
8    6000
7    6000
6    6000
5    6000
4    6000
3    6000
2    6000
1    6000
0    6000
Name: label, dtype: int64

In [13]:
display(TrainValidationset.select_dtypes(include=[np.number]).describe())

label        pixel1        pixel2        pixel3        pixel4  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean       4.500000      0.000900      0.006150      0.035333      0.101933   
std        2.872305      0.094689      0.271011      1.222324      2.452871   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      0.000000      0.000000      0.000000      0.000000   
50%        4.500000      0.000000      0.000000      0.000000      0.000000   
75%        7.000000      0.000000      0.000000      0.000000      0.000000   
max        9.000000     16.000000     36.000000    226.000000    164.000000   

             pixel5        pixel6        pixel7        pixel8        pixel9  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean       0.247967      0.411467      0.805767      2.198283      5.682000   
std        4.306912      5.836188      8.215169     14.093378     23.819481   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max      227.000000    230.000000    224.000000    255.000000    254.000000   

       ...      pixel775      pixel776      pixel777      pixel778  \
count  ...  60000.000000  60000.000000  60000.000000  60000.000000   
mean   ...     34.625400     23.300683     16.588267     17.869433   
std    ...     57.545242     48.854427     41.979611     43.966032   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...     58.000000      9.000000      0.000000      0.000000   
max    ...    255.000000    255.000000    255.000000    255.000000   

           pixel779      pixel780      pixel781      pixel782      pixel783  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean      22.814817     17.911483      8.520633      2.753300      0.855517   
std       51.830477     45.149388     29.614859     17.397652      9.356960   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max      255.000000    255.000000    255.000000    255.000000    255.000000   

          pixel784  
count  60000.00000  
mean       0.07025  
std        2.12587  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        0.00000  
max      170.00000  

[8 rows x 785 columns]

Task 4: Diving the data set into train and validate data sets (70:30)

In [15]:
Y = TrainValidationset["label"]

In [31]:
X = TrainValidationset.iloc[:,1:785]

In [57]:
X_train, X_validate, y_train, y_validate \
    = train_test_split(X, Y, random_state=0, \
                                    train_size = 0.7)

Task 5: Building a Decision Tree Model

In [60]:
DecisionTree1 = tree.DecisionTreeClassifier(criterion="entropy", max_depth=150)
DecisionTree1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=150,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

Task 5.1: Assessing the performance of the DecisionTree1 on the *train set*

In [61]:
y_pred = DecisionTree1.predict(X_train)
accuracy = \
metrics.accuracy_score(y_train, y_pred) # , normalize=True, sample_weight=None
print("Accuracy: " +  str(accuracy))
print(metrics.classification_report(y_train, y_pred))
print(metrics.confusion_matrix(y_train, y_pred))
print("Confusion Matrix")
pd.crosstab(y_train, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4201
           1       1.00      1.00      1.00      4157
           2       1.00      1.00      1.00      4192
           3       1.00      1.00      1.00      4151
           4       1.00      1.00      1.00      4235
           5       1.00      1.00      1.00      4214
           6       1.00      1.00      1.00      4213
           7       1.00      1.00      1.00      4211
           8       1.00      1.00      1.00      4205
           9       1.00      1.00      1.00      4221

    accuracy                           1.00     42000
   macro avg       1.00      1.00      1.00     42000
weighted avg       1.00      1.00      1.00     42000

[[4201    0    0    0    0    0    0    0    0    0]
 [   0 4157    0    0    0    0    0    0    0    0]
 [   0    0 4192    0    0    0    0    0    0    0]
 [   0    0    0 4151    0    0    0    0    0    0]
 [   0    0    

Predicted     0     1     2     3     4     5     6     7     8     9    All
True                                                                        
0          4201     0     0     0     0     0     0     0     0     0   4201
1             0  4157     0     0     0     0     0     0     0     0   4157
2             0     0  4192     0     0     0     0     0     0     0   4192
3             0     0     0  4151     0     0     0     0     0     0   4151
4             0     0     0     0  4235     0     0     0     0     0   4235
5             0     0     0     0     0  4214     0     0     0     0   4214
6             0     0     0     0     0     0  4213     0     0     0   4213
7             0     0     0     0     0     0     0  4211     0     0   4211
8             0     0     0     0     0     0     0     0  4205     0   4205
9             0     0     0     0     0     0     0     0     0  4221   4221
All        4201  4157  4192  4151  4235  4214  4213  4211  4205  4221  42000

Task 6: Evaluating the performance of the DecisionTree1 on the *validate set*

In [62]:
y_pred = DecisionTree1.predict(X_validate)
accuracy = metrics.accuracy_score(y_validate, y_pred) 
print("Accuracy: " +  str(accuracy))
print(metrics.classification_report(y_validate, y_pred))
print(metrics.confusion_matrix(y_validate, y_pred))
print("Confusion Matrix")
pd.crosstab(y_validate, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Accuracy: 0.805
              precision    recall  f1-score   support

           0       0.74      0.76      0.75      1799
           1       0.94      0.94      0.94      1843
           2       0.68      0.71      0.69      1808
           3       0.81      0.80      0.81      1849
           4       0.69      0.69      0.69      1765
           5       0.92      0.90      0.91      1786
           6       0.56      0.54      0.55      1787
           7       0.88      0.88      0.88      1789
           8       0.91      0.92      0.92      1795
           9       0.90      0.92      0.91      1779

    accuracy                           0.81     18000
   macro avg       0.80      0.80      0.80     18000
weighted avg       0.80      0.81      0.80     18000

[[1359    8   44   95   14    2  251    0   26    0]
 [  13 1735   13   52    8    0   16    0    6    0]
 [  37    7 1280   25  213    0  225    0   19    2]
 [  92   60   39 1483   93    2   61    0   17    2]
 [  22    9  

Predicted     0     1     2     3     4     5     6     7     8     9    All
True                                                                        
0          1359     8    44    95    14     2   251     0    26     0   1799
1            13  1735    13    52     8     0    16     0     6     0   1843
2            37     7  1280    25   213     0   225     0    19     2   1808
3            92    60    39  1483    93     2    61     0    17     2   1849
4            22     9   247    90  1210     0   173     0    12     2   1765
5             5     2     1     2     1  1611     4    93    18    49   1786
6           288    11   229    60   189     4   961     0    45     0   1787
7             0     0     0     0     0    83     0  1577     5   124   1789
8            14     5    24    20    20    14    32    11  1646     9   1795
9             1     0     0     0     0    41     0   102     7  1628   1779
All        1831  1837  1877  1827  1748  1757  1723  1783  1801  1816  18000

Task 7: Using Grid Search to tune the hyperparameters of DecisionTree1

In [66]:
param_grid ={'criterion': ['gini', "entropy"], \
             'max_depth': list(range(10, 150, 20)), \
             'min_samples_split': [500] }
my_tuned_tree = GridSearchCV(tree.DecisionTreeClassifier(), \
                                param_grid, cv=2, verbose = 0, \
                            return_train_score=True)
my_tuned_tree.fit(X_train, y_train)
print("Best parameters set found on training set:")
display(my_tuned_tree.best_params_)
display(my_tuned_tree.best_score_)
display(my_tuned_tree.cv_results_)

Best parameters set found on training set:


{'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 500}

0.7547857142857143

{'mean_fit_time': array([3.99058294, 6.41973245, 7.8013587 , 7.49406934, 7.27488995,
        7.09505856, 6.81008613, 5.11624324, 5.58918011, 5.70152402,
        5.62065578, 5.95250082, 5.95002091, 5.5266844 ]),
 'std_fit_time': array([5.77962399e-02, 2.02655792e-06, 2.83978224e-01, 4.83601093e-01,
        1.06195688e-01, 2.85781622e-02, 4.66238260e-02, 4.46331501e-03,
        5.38166761e-02, 1.15567923e-01, 8.03735256e-02, 8.03518295e-02,
        1.01183534e-01, 1.19288325e-01]),
 'mean_score_time': array([0.04687345, 0.0508275 , 0.06200075, 0.05307341, 0.05878949,
        0.0488559 , 0.05158389, 0.05580986, 0.05232894, 0.05406427,
        0.0498482 , 0.05133641, 0.05703998, 0.05332017]),
 'std_score_time': array([0.00024951, 0.00321245, 0.00099254, 0.00297713, 0.00620675,
        0.00024784, 0.00148809, 0.00670421, 0.00124061, 0.        ,
        0.00024807, 0.00074422, 0.00297618, 0.00272822]),
 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gi

Task 7.1: Evaluating DecisionTree2 (Gini and max depth 10)

In [68]:
DecisionTree2 = tree.DecisionTreeClassifier(criterion="gini", max_depth=10)
DecisionTree2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

Task 7.2: Assessing the performance of the DecisionTree2 on the *train set*

In [69]:
y_pred = DecisionTree2.predict(X_train)
accuracy = \
metrics.accuracy_score(y_train, y_pred) 
print("Accuracy: " +  str(accuracy))
print(metrics.classification_report(y_train, y_pred))
print(metrics.confusion_matrix(y_train, y_pred))
print("Confusion Matrix")
pd.crosstab(y_train, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Accuracy: 0.8503095238095238
              precision    recall  f1-score   support

           0       0.81      0.86      0.84      4201
           1       0.99      0.95      0.97      4157
           2       0.76      0.69      0.72      4192
           3       0.85      0.86      0.86      4151
           4       0.66      0.80      0.72      4235
           5       0.98      0.93      0.95      4214
           6       0.67      0.58      0.62      4213
           7       0.89      0.96      0.92      4211
           8       0.96      0.95      0.96      4205
           9       0.96      0.92      0.94      4221

    accuracy                           0.85     42000
   macro avg       0.85      0.85      0.85     42000
weighted avg       0.85      0.85      0.85     42000

[[3633    5   49  131   31    1  331    2   17    1]
 [  22 3959   12  135    7    0   21    0    1    0]
 [  32    1 2886   33  909    4  303    0   24    0]
 [ 165   22   59 3560  191    3  137    0   12    2]


Predicted     0     1     2     3     4     5     6     7     8     9    All
True                                                                        
0          3633     5    49   131    31     1   331     2    17     1   4201
1            22  3959    12   135     7     0    21     0     1     0   4157
2            32     1  2886    33   909     4   303     0    24     0   4192
3           165    22    59  3560   191     3   137     0    12     2   4151
4            18     4   275   166  3376     2   373     0    21     0   4235
5             0     1     3     2     1  3924     3   202    17    61   4214
6           570     5   491   120   521     0  2459     1    46     0   4213
7             0     0     1     0     0    51     1  4045     7   106   4211
8            15     1    29    27    50    19    49    14  4000     1   4205
9             5     0     7     0     1    15     7   304    11  3871   4221
All        4460  3998  3812  4174  5087  4019  3684  4568  4156  4042  42000

Task 7.3: Assessing the performance of the DecisionTree2 on the *validate data*

In [70]:
y_pred = DecisionTree2.predict(X_validate)
accuracy = metrics.accuracy_score(y_validate, y_pred) # , normalize=True, sample_weight=None
print("Accuracy: " +  str(accuracy))
print(metrics.classification_report(y_validate, y_pred))
print(metrics.confusion_matrix(y_validate, y_pred))
print("Confusion Matrix")
pd.crosstab(y_validate, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Accuracy: 0.8069444444444445
              precision    recall  f1-score   support

           0       0.76      0.79      0.78      1799
           1       0.98      0.93      0.95      1843
           2       0.72      0.69      0.70      1808
           3       0.81      0.83      0.82      1849
           4       0.63      0.75      0.69      1765
           5       0.92      0.87      0.89      1786
           6       0.57      0.50      0.53      1787
           7       0.85      0.92      0.89      1789
           8       0.92      0.90      0.91      1795
           9       0.92      0.89      0.91      1779

    accuracy                           0.81     18000
   macro avg       0.81      0.81      0.81     18000
weighted avg       0.81      0.81      0.81     18000

[[1427    2   39   71   27    1  213    0   16    3]
 [  13 1708    8   75   11    1   20    0    7    0]
 [   9    1 1244   21  366    2  143    0   21    1]
 [  90   20   21 1526  110    8   68    0    6    0]


Predicted     0     1     2     3     4     5     6     7     8     9    All
True                                                                        
0          1427     2    39    71    27     1   213     0    16     3   1799
1            13  1708     8    75    11     1    20     0     7     0   1843
2             9     1  1244    21   366     2   143     0    21     1   1808
3            90    20    21  1526   110     8    68     0     6     0   1849
4            13     0   145    96  1319     0   173     0    18     1   1765
5             3     1     2     9     0  1545     4   140    25    57   1786
6           311     8   251    57   227     4   896     0    33     0   1787
7             1     0     0     0     0    58     1  1651     5    73   1789
8            12     0    25    24    24    30    47    10  1621     2   1795
9             2     0     4     0     1    26     3   141    14  1588   1779
All        1881  1740  1739  1879  2085  1675  1568  1942  1766  1725  18000

Task 8: Experimenting with Random Forests

In [71]:
RandomForest1 = ensemble.RandomForestClassifier(n_estimators=100, \
                                           max_features = 10,\
                                           min_samples_split=500)
RandomForest1.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features=10, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=500,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [73]:
y_pred = RandomForest1.predict(X_validate)
print(metrics.classification_report(y_validate, y_pred))
print("Confusion Matrix")
pd.crosstab(y_validate, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

              precision    recall  f1-score   support

           0       0.74      0.80      0.77      1799
           1       1.00      0.92      0.96      1843
           2       0.72      0.77      0.74      1808
           3       0.74      0.91      0.82      1849
           4       0.69      0.77      0.73      1765
           5       0.95      0.92      0.93      1786
           6       0.71      0.39      0.50      1787
           7       0.90      0.89      0.90      1789
           8       0.91      0.96      0.94      1795
           9       0.91      0.93      0.92      1779

    accuracy                           0.83     18000
   macro avg       0.83      0.83      0.82     18000
weighted avg       0.83      0.83      0.82     18000

Confusion Matrix


Predicted     0     1     2     3     4     5    6     7     8     9    All
True                                                                       
0          1434     1    38   190    12     2   85     0    37     0   1799
1             2  1700    41    89     6     0    4     0     1     0   1843
2             7     0  1387    13   296     0   78     0    27     0   1808
3            49     3    18  1674    61     0   39     0     5     0   1849
4             6     0   163   160  1356     0   66     0    14     0   1765
5             0     1     0     1     0  1650    0    93    14    27   1786
6           424     2   264   119   213     2  696     0    67     0   1787
7             0     0     0     0     0    54    0  1599     3   133   1789
8             3     0    24    10     9     5   11     2  1728     3   1795
9             0     0     1     0     0    31    0    85     3  1659   1779
All        1925  1707  1936  2256  1953  1744  979  1779  1899  1822  18000

Task 9: Experimenting with feature engineering 

Task 9.1: Experimenting with feature engineering (increasing number of trees)

In [74]:
RandomForest2 = ensemble.RandomForestClassifier(n_estimators=200, \
                                           max_features = 10,\
                                           min_samples_split=500)
RandomForest2.fit(X_train,y_train)
y_pred = RandomForest2.predict(X_validate)
print(metrics.classification_report(y_validate, y_pred))
print("Confusion Matrix")
pd.crosstab(y_validate, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

              precision    recall  f1-score   support

           0       0.75      0.80      0.77      1799
           1       1.00      0.92      0.96      1843
           2       0.72      0.75      0.74      1808
           3       0.74      0.91      0.82      1849
           4       0.69      0.76      0.72      1765
           5       0.95      0.93      0.94      1786
           6       0.70      0.40      0.51      1787
           7       0.90      0.89      0.90      1789
           8       0.91      0.96      0.93      1795
           9       0.91      0.94      0.92      1779

    accuracy                           0.83     18000
   macro avg       0.83      0.83      0.82     18000
weighted avg       0.83      0.83      0.82     18000

Confusion Matrix


Predicted     0     1     2     3     4     5     6     7     8     9    All
True                                                                        
0          1443     1    39   179    11     2    82     0    42     0   1799
1             3  1697    40    89     8     0     5     0     1     0   1843
2             5     0  1361    16   310     0    88     0    28     0   1808
3            45     1    18  1686    57     0    38     0     4     0   1849
4             6     1   154   170  1344     0    76     0    14     0   1765
5             0     0     0     1     0  1653     0    89    14    29   1786
6           430     2   243   111   218     2   710     0    71     0   1787
7             0     0     0     0     0    55     0  1593     3   138   1789
8             3     0    24    14    10     7     9     2  1725     1   1795
9             0     0     1     0     0    25     0    82     3  1668   1779
All        1935  1702  1880  2266  1958  1744  1008  1766  1905  1836  18000

Most of the problems are in categories (0) T-shirt/top, (2) Pullover, (4)
Coat and (6) Shirt.

Task 9.2: Experimenting with feature engineering (increasing max depth)

In [75]:
RandomForest3 = ensemble.RandomForestClassifier(n_estimators=100, \
                                           max_features = 15,\
                                           min_samples_split=500)
RandomForest3.fit(X_train,y_train)
y_pred = RandomForest3.predict(X_validate)
print(metrics.classification_report(y_validate, y_pred))
print("Confusion Matrix")
pd.crosstab(y_validate, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

              precision    recall  f1-score   support

           0       0.75      0.80      0.78      1799
           1       1.00      0.92      0.96      1843
           2       0.72      0.75      0.74      1808
           3       0.75      0.91      0.82      1849
           4       0.69      0.78      0.73      1765
           5       0.95      0.93      0.94      1786
           6       0.72      0.40      0.51      1787
           7       0.91      0.89      0.90      1789
           8       0.90      0.96      0.93      1795
           9       0.91      0.94      0.93      1779

    accuracy                           0.83     18000
   macro avg       0.83      0.83      0.82     18000
weighted avg       0.83      0.83      0.82     18000

Confusion Matrix


Predicted     0     1     2     3     4     5    6     7     8     9    All
True                                                                       
0          1446     1    39   169    11     2   88     0    43     0   1799
1             2  1697    39    94     3     0    6     0     2     0   1843
2             6     0  1362    14   325     0   73     0    28     0   1808
3            45     2    23  1686    59     0   31     0     3     0   1849
4             6     1   147   158  1373     0   66     0    14     0   1765
5             0     0     0     2     0  1659    0    78    19    28   1786
6           420     2   260   108   211     1  709     0    76     0   1787
7             0     0     0     0     0    59    0  1594     4   132   1789
8             3     0    24     9     8     5   12     4  1728     2   1795
9             0     0     1     1     0    25    0    77     2  1673   1779
All        1928  1703  1895  2241  1990  1751  985  1753  1919  1835  18000

Task 9.3: Experimenting with feature engineering (reducing min samples split)

In [76]:
RandomForest4 = ensemble.RandomForestClassifier(n_estimators=100, \
                                           max_features = 10,\
                                           min_samples_split=100)
RandomForest4.fit(X_train,y_train)
y_pred = RandomForest4.predict(X_validate)
print(metrics.classification_report(y_validate, y_pred))
print("Confusion Matrix")
pd.crosstab(y_validate, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

              precision    recall  f1-score   support

           0       0.79      0.84      0.81      1799
           1       0.99      0.94      0.97      1843
           2       0.75      0.80      0.77      1808
           3       0.83      0.91      0.87      1849
           4       0.73      0.80      0.77      1765
           5       0.96      0.94      0.95      1786
           6       0.73      0.50      0.60      1787
           7       0.92      0.91      0.92      1789
           8       0.93      0.97      0.95      1795
           9       0.92      0.94      0.93      1779

    accuracy                           0.86     18000
   macro avg       0.86      0.86      0.85     18000
weighted avg       0.86      0.86      0.85     18000

Confusion Matrix


Predicted     0     1     2     3     4     5     6     7     8     9    All
True                                                                        
0          1508     2    29    95     8     3   123     0    31     0   1799
1             1  1741    32    55     4     0     8     0     2     0   1843
2             7     0  1443    15   249     0    75     0    19     0   1808
3            48     2    19  1687    58     0    33     0     2     0   1849
4             6     1   142   121  1412     0    71     0    12     0   1765
5             0     0     0     2     0  1678     0    69    13    24   1786
6           335     4   249    55   188     1   900     0    55     0   1787
7             0     0     0     0     0    41     0  1630     3   115   1789
8             2     0    16     8     7     4    17     3  1736     2   1795
9             0     0     1     0     0    25     0    70     2  1681   1779
All        1907  1750  1931  2038  1926  1752  1227  1772  1875  1822  18000

Task 10: Evaluating the best model (RandomForest4) on the test data set

In [78]:
Testset = pd.read_csv('fashion-mnist_test.csv')
Y_test = Testset["label"]
X_test = Testset.iloc[:,1:785]

In [82]:
y_pred = RandomForest4.predict(X_test)
print(metrics.classification_report(Y_test, y_pred))
print("Confusion Matrix")
pd.crosstab(Y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

              precision    recall  f1-score   support

           0       0.78      0.83      0.80      1000
           1       0.98      0.95      0.97      1000
           2       0.77      0.77      0.77      1000
           3       0.84      0.92      0.88      1000
           4       0.75      0.83      0.79      1000
           5       0.96      0.93      0.94      1000
           6       0.72      0.52      0.61      1000
           7       0.90      0.90      0.90      1000
           8       0.93      0.97      0.95      1000
           9       0.91      0.93      0.92      1000

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000

Confusion Matrix


Predicted     0    1     2     3     4    5    6     7     8     9    All
True                                                                     
0           830    1    16    50     4    1   78     0    20     0   1000
1             3  952    13    25     2    1    3     0     1     0   1000
2             7    1   773    10   139    1   56     0    13     0   1000
3            21   10     9   915    26    0   17     0     2     0   1000
4             0    2    73    50   830    0   40     0     5     0   1000
5             0    0     0     0     0  929    0    49     8    14   1000
6           206    3   113    35    98    0  522     0    23     0   1000
7             0    0     0     0     0   22    0   898     0    80   1000
8             1    1    11     2     4    2    8     4   966     1   1000
9             0    0     0     0     0   12    1    51     4   932   1000
All        1068  970  1008  1087  1103  968  725  1002  1042  1027  10000

Thank you.